In [1]:
import csv
import pandas as pd
import openpyxl

# Prep Works

In [2]:
final_dict = {
     "Regions" : 1,
     "Province" : 2,
     "Municipality" : 3 ,
     "Barangay" : 4,
     "PSGC" : 5, #will need data from another file
     "Owner Name" : 6 ,
     "Owner Type" : 7,
     "Machine/Facility" : 8,
     "Brand" : 9,
     "Serial" : 10,
     "Capacity" : 11,
     "Capacity Unit" : 12 , # will need another dictionary
     "Condition" : 13 ,
     "Use of Facility" : 14,
     "Mode of Acquisition" : 15,
     "Year Acquired" : 16,
     "Engine Brand" : 17,
     "Engine Serial" : 18,
     "Rated Power" : 19
    
}

In [3]:
raw_dict = {
     "REGION" : 1,
     "PROVINCE" : 2,
     "MUNICIPALITY" : 3 ,
     "BARANGAY" : 4,
     "NAME OF RESPONDENT" : 5,
     "TYPE OF OWNER" : 7 ,
     "HT TYPE" : 11, #Facility
     "HT CAPACITY" : 12, #Capacity
     "HT SERIAL" : 13,
     "HT BRAND/MAKE" : 14,
     "HT MODE OF A3Q" : 15,
     "HT YEAR" : 18,
     "HT USE OF FACILITY" : 19 ,
     "H FACILITY CONDITION" : 20 ,
     "HT ENGINE BRAND" : 23,
     "HT ENGINE POWER" : 24 #Rated Power
}

In [4]:
column_names = ["REGION",
     "PROVINCE",
     "MUNICIPALITY",
     "BARANGAY ",
     "NAME OF RESPONDENT",
     "TYPE OF OWNER",
     "HT TYPE", #Facility
     "HT CAPACITY", #Capacity
     "HT SERIAL",
     "HT BRAND/MAKE",
     "HT MODE OF A3Q",
     "HT YEAR",
     "HT USE OF FACILITY",
     "HT ENGINE BRAND",
     "HT ENGINE POWER"] #Rated Power]

### Get each sheet headers to ensure that all sheets have the same headers

In [5]:
def get_sheet_headers(file_path):
    xls = pd.ExcelFile(file_path)
    sheet_headers = {}
    
    for sheet_name in xls.sheet_names:
        # Read the first row of each sheet to get headers
        df = pd.read_excel(file_path, sheet_name=sheet_name, nrows=1)
        headers = df.columns.tolist()

        # Store the headers in the dictionary
        sheet_headers[sheet_name] = headers
        
    return sheet_headers

In [6]:
temp_library = ""

### Sample Use

In [7]:
#Raw File Path
raw_file = 'C:/Users/ICTS-Nigel/Desktop/Desktop Litters/Files/ZAMBOANGA SIBUGAY3.xlsx'

In [8]:
sheetnames = []

In [9]:
#

headers_dict = get_sheet_headers(raw_file)

counter = 1
# Print headers for each sheet
for sheet_name, headers in headers_dict.items():
    sheetnames.append(sheet_name)
    hit = 0
    for i in headers: 
        match( i ):
            case 'REGION' :
                if(counter != raw_dict['REGION']) :
                    hit+= 1
                break;
            
            case 'PROVINCE'  :
                if(counter != raw_dict['PROVINCE']) :
                    hit+= 1
                break;
            case 'MUNICIPALITY' :
                if(counter != raw_dict['MUNICIPALITY']) :
                    hit+= 1
                break;
            case 'BARANGAY':
                if(counter != raw_dict['BARANGAY']) :
                    hit+= 1
                break;
            case 'NAME OF RESPONDENT':
                if(counter != raw_dict['NAME OF RESPONDEN']) :
                    hit+= 1
                break;
            case 'TYPE OF OWNER':
                if(counter != raw_dict['TYPE OF OWNER']) :
                    hit+= 1
                break;
            case 'HT TYPE':
                if(counter != raw_dict['HT TYPE']) :
                    hit+= 1
                break;
            case 'HT CAPACITY':
                if(counter != raw_dict['HT CAPACITY']) :
                    hit+= 1
                break;
            case 'HT SERIAL':
                if(counter != raw_dict['HT SERIAL']) :
                    hit+= 1
                break;
            case 'HT BRAND/MAKE':
                if(counter != raw_dict['HT BRAND/MAKE']) :
                    hit+= 1
                break;
            case 'HT MODE OF A3Q':
                if(counter != raw_dict['HT MODE OF A3Q']) :
                    hit+= 1
                break;
            case 'HT YEAR':
                if(counter != raw_dict['HT YEAR']) :
                    hit+= 1
                break;
            case 'HT USE OF FACILITY':
                if(counter != raw_dict['HT USE OF FACILITY']) :
                    hit+= 1
                break;
            case 'H FACILITY CONDITION':
                if(counter != raw_dict['H FACILITY CONDITION']) :
                    hit+= 1
                break;
            case 'HT ENGINE BRAND':
                if(counter != raw_dict['HT ENGINE BRAND']) :
                    hit+= 1
                break;
            case 'HT ENGINE POWER':
                if(counter != raw_dict['HT ENGINE POWER']) :
                    hit+= 1
                break;
       
    if(hit == 0):
        print(f"Sheet: {sheet_name}")
        #print(f"Headers: {headers}")
print("done")

Sheet: KAbasalan
Sheet: NAGA
Sheet: IPIL
Sheet: TUNGAWAN
Sheet: R.T.LIM
Sheet: TITAY
Sheet: PAYAO
Sheet: MABUHAY
Sheet: SIAY
Sheet: TALUSAN
Sheet: OLUTANGA
Sheet: ALICIA
Sheet: DIPLAHAN
Sheet: MALANGAS
Sheet: IMELDA
Sheet: BUUG
done

In [10]:
print(sheetnames)

['KAbasalan', 'NAGA', 'IPIL', 'TUNGAWAN', 'R.T.LIM', 'TITAY', 'PAYAO', 'MABUHAY', 'SIAY', 'TALUSAN', 'OLUTANGA', 'ALICIA', 'DIPLAHAN', 'MALANGAS', 'IMELDA', 'BUUG']

In [11]:
def get_columns(sheet_name):
    # Read the Excel file
    df = pd.read_excel(raw_file, sheet_name=sheet_name)
    
    # Extract specific columns for each row
    selected_data = df[column_names]
    
    return selected_data

In [12]:
extracted_data = get_columns('KAbasalan')

In [71]:
#extracted_data.loc[:,'MUNICIPALITY'].tolist()
column_names

In [ ]:
def print(output_file):
    # Read the input Excel file
    df_input = pd.read_excel(input_file, sheet_name=sheet_name)

    # Create a new Excel file or overwrite an existing one
    with pd.ExcelWriter(output_file, engine='xlsxwriter') as writer:
        # Write the DataFrame to the Excel file
        df_input.to_excel(writer, sheet_name=sheet_name, index=False)

# Example usage
input_excel_file = 'path/to/input_file.xlsx'
output_excel_file = 'path/to/output_file.xlsx'
sheet_name = 'Sheet1'  # Change this to the name of the sheet you want to transfer

copy_rows(input_excel_file, output_excel_file, sheet_name)

In [61]:
print(get_columns("KAbasalan"))

    REGION           PROVINCE MUNICIPALITY BARANGAY     NAME OF RESPONDENT  \
0      NaN                NaN          NaN       NaN                   NaN
1      NaN  ZAMBOANGA SIBUGAY    KABASALAN     POKIA  MILADEL S. CAPITANIA
2      NaN                NaN          NaN       NaN                   NaN
3      NaN                NaN          NaN       NaN                   NaN
4      NaN                NaN          NaN       NaN                   NaN
5      NaN                NaN          NaN       NaN                   NaN
6      NaN                NaN          NaN       NaN    GUILLERMO S. DANDA
7      NaN                NaN          NaN       NaN                   NaN
8      NaN                NaN          NaN       NaN                   NaN
9      NaN                NaN          NaN       NaN                   NaN
10     NaN                NaN          NaN       NaN                   NaN
11     NaN                NaN          NaN       NaN                   NaN
12     NaN                NaN          NaN       NaN                   NaN
13     NaN                NaN          NaN       NaN                   NaN
14     NaN                NaN          NaN     CBCIA  EDUARDO V. CABILLEZA
15     NaN                NaN          NaN       NaN                   NaN
16     NaN                NaN          NaN       NaN                   NaN
17     NaN                NaN          NaN       NaN                   NaN
18     NaN                NaN          NaN       NaN                   NaN
19     NaN                NaN          NaN       NaN                   NaN
20     NaN                NaN          NaN     PPMPC         CIELITO DARUG
21     NaN                NaN          NaN   GARBMPC    TEODORO A. SABANAL

    TYPE OF OWNER                                            HT TYPE  \
0             NaN  Hand Tractor Type\n1. Kuliglig - type\n2. Mini...
1             3.0                                                NaN
2             3.0                                                NaN
3             3.0                                                  1
4             3.0                                                NaN
5             3.0                                                NaN
6             2.0                                                  1
7             2.0                                                  1
8             2.0                                                  3
9             2.0                                                NaN
10            2.0                                                NaN
11            2.0                                                NaN
12            2.0                                                NaN
13            2.0                                                NaN
14            2.0                                                NaN
15            2.0                                                  3
16            2.0                                                  1
17            2.0                                                NaN
18            2.0                                                NaN
19            2.0                                                NaN
20            2.0                                                  1
21            2.0                                                  1

                                          HT CAPACITY  \
0   Hand Tractor  Capacity, in numer of hectares p...
1                                                 NaN
2                                                 NaN
3                                                 1.5
4                                                 NaN
5                                                 NaN
6                                                   4
7                                                   4
8                                                   1
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                              1-1.5
16                                              1-1.5
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN

                       HT SERIAL              HT BRAND/MAKE  \
0   Hand Tractor  Serial Numer\n  Hand Tractor rand or Make
1                            NaN                        NaN
2                            NaN                        NaN
3           KWP 50000 TLCL 07777                     KUBOTA
4                            NaN                        NaN
5                            NaN                        NaN
6                 KV-80-20H03400              SUPER HARABAS
7                         KV - 8              SUPER HARABAS
8                            101                   CHINLONG
9                            NaN                        NaN
10                           NaN                        NaN
11                           NaN                        NaN
12                           NaN                        NaN
13                           NaN                        NaN
14                           NaN                        NaN
15                           NaN                        NaN
16                           NaN                        NaN
17                           NaN                        NaN
18                           NaN                        NaN
19                           NaN                        NaN
20                           NaN                        NaN
21                           NaN                        NaN

                                       HT MODE OF A3Q  \
0   HAnd TraCtor Mode of Acquisition Cost\n1. Gran...
1                                                 NaN
2                                                 NaN
3                                                   1
4                                                 NaN
5                                                 NaN
6                                                   1
7                                                   1
8                                                   1
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                  3
16                                                  3
17                                                NaN
18                                                NaN
19                                                NaN
20                                                  1
21                                                  1

                       HT YEAR  \
0   Hand Tractor Year Acquired
1                          NaN
2                          NaN
3                         2021
4                          NaN
5                          NaN
6                         2020
7                         2020
8                         2020
9                          NaN
10                         NaN
11                         NaN
12                         NaN
13                         NaN
14                         NaN
15                        2017
16                        2017
17                         NaN
18                         NaN
19                         NaN
20                        2016
21                        2017

                                   HT USE OF FACILITY  \
0   Hand Tractor Purpose\n1. Private use\n2. Custo...
1                                                 NaN
2                                                 NaN
3                                                   3
4                                                 NaN
5                                                 NaN
6                                                   4
7                                                   4
8                                                   4
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                  4
16                                                  4
17                                                NaN
18                                                NaN
19                                                NaN
20                                                  4
21                                                  4

             HT ENGINE BRAND                         HT ENGINE POWER
0   Hand tractor engine rand  Hand tractor engine power rating, hp\n
1                        NaN                                     NaN
2                        NaN                                     NaN
3                     YANMAR                                   12 hp
4                        NaN                                     NaN
5                        NaN                                     NaN
6                     KUVICO                                    8 hp
7                     KUVICO                                    8 hp
8                        PAT                                    8 hp
9                        NaN                                     NaN
10                       NaN                                     NaN
11                       NaN                                     NaN
12                       NaN                                     NaN
13                       NaN                                     NaN
14                       NaN                                     NaN
15        BRIGGS AND STRATON                                    10HP
16                    KOBIKO                                    15HP
17                       NaN                                     NaN
18                       NaN                                     NaN
19                       NaN                                     NaN
20                       NaN                                     NaN
21                       NaN                                     NaN